### ISSUE TITLE
Spring Modulith with MongoDB requires TransactionManager even with transactions disabled

### ISSUE THREAD

**Issue by janpetryk** [spring-projects/spring-modulith#1021]
```
spring:
  modulith:
    events:
      republish-outstanding-events-on-restart: true
      externalization:
        enabled: true
      mongodb:
        transaction-management:
          enabled: false
```

**Expected Behavior**
The application should start successfully since transactions are explicitly disabled.

**Actual Behavior**
Application fails to start with:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
A component required a bean of type 'org.springframework.transaction.TransactionManager' that could not be found.
```

**Environment**

Spring Boot: 3.2.2
Spring Modulith: 1.3.1
MongoDB

**Suggestion**
Add support for running without a TransactionManager when transactions are disabled via properties, eliminating the need for custom configuration.
